### ISSUE TITLE
Large read and write operations may be too slow

### ISSUE THREAD

**Issue by ShreksHellraiser** [MasonGulu/cctech#4]
Currently read and write operations are in an iterative loop over each character. If there's a sufficient enough amount of data transferred (>2MB) then CC may terminate your program and say that CC may be installed incorrectly. This is a known issue and the current workaround is just to transfer smaller amounts of data for now.

**Comment by BingusManLeftToenail** [comment]
How DARE there be bugs in the Alpha. HOW DARE YOU! I didn't pay for THIS!? (/j)

**Comment by ShreksHellraiser** [comment]
Hah this is nothing, 0.1.1 didn't have hardness values set so the blocks would break instantly (and the reel to reel didn't drop itself when broken)

**Comment by ShreksHellraiser** [comment]
I've done more testing. This issue only seems to appear when reading more than 20MB, which is much larger than the default tape sizes, and larger than any foreseeable future expansions. This issue won't apply to sector media, as those will be read using a different method. I don't think this issue needs to be fixed.

**Comment by SquidDev** [comment]
You could speed this up a lot just by reading/writing multiple bytes at once using a `ByteBuffer` rather than converting to/from a `String`. This way it's just a memory copy, which should be as fast as you can get.

**Comment by ShreksHellraiser** [comment]
This is now fixed
