### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by awesomebossdj7** [MasonGulu/cctech#8]
if you guys are taking suggestions, I would LOVE to see a keyboard peripheral that works like the keyboards in moarperipherals in 1.7.10

**Comment by MasonGulu** [comment]
This mod is not and will not ever be available for 1.7.10

**Comment by ShreksHellraiser** [comment]
https://github.com/SamsTheNerd/ducky-periphs
Ducky Peripherals might interest you then, it adds customizable keyboards

**Comment by ShreksHellraiser** [comment]
Thank you for the suggestion, however this feature is already covered by Ducky Peripherals in a way that's much better than anything I'd implement.
